gcp.project-id=${GCP_PROJECT_ID}

spring.datasource.url=jdbc:mysql://localhost:3306/evalit?createDatabaseIfNotExist=true
spring.datasource.username=${MYSQL_USER:evalit_user}
spring.datasource.password=${MYSQL_PASSWORD:evalit_password}
spring.jpa.hibernate.ddl-auto=update

google.oauth.client-id=${GOOGLE_OAUTH_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
google.oauth.redirect-uri=${SERVER_IP_WITH_NIP}/google/oauth/callback

spring.security.oauth2.client.registration.google.client-id=${google.oauth.client-id}
spring.security.oauth2.client.registration.google.client-secret=${google.oauth.client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
