spring.application.name=eval-it
spring.profiles.active=local
google.oauth.redirect-uri=http://localhost:8080/google/oauth/callback
google.oauth.owner-id=client1
google.forms.application-name=eval-it
server.port=8080
google.oauth.client-id=755037000680-pcfmdm2t6gre9nai9demvbf7phb839g8.apps.googleusercontent.com
google.oauth.client-secret=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
spring.datasource.url=jdbc:mysql://localhost:3306/survey_db?createDatabaseIfNotExist=true&serverTimezone=Europe/Istanbul


spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
